# Generated by Django 3.2.8 on 2021-10-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='igpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('taxa', models.DecimalField(decimal_places=10, max_digits=19)),
                ('multiplicadorAbsoluto', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
